name: Build and push docker image to Artifact Registry
on:
  push:
    branches: [main]
jobs:
  run:
    name: "Workload Identity Job"
    permissions:
      id-token: write
      contents: read
    runs-on: "ubuntu-latest"
    steps:
      - name: "Auth in GCP"
        id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          token_format: "access_token"
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_NAME }}
          service_account: ${{ secrets.GCP_WORKLOAD_IDENTITY_SA_EMAIL }}

      - name: "Docker login"
        run: |
          echo '${{ steps.auth.outputs.access_token }}' | docker login -u oauth2accesstoken --password-stdin https://gcr.io
  # build-push-artifact-registry:
  #   name: Build and push to Artifact Registry
  #   runs-on: ubuntu-latest
  #   env:
  #     IMAGE_NAME: hello-app
  #     PROJECT_ID: cloud-core-376009
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Build Docker Image
  #       run: docker build -t $IMAGE_NAME:latest .
