name: Build and push docker image to Artifact Registry

on:
  push:
    tags:
      - v*.*.*

jobs:
  authorize:
    name: Authorize using Workflow Identity Federation
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3

      - id: auth
        name: Auth in GCP
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_NAME }}
          service_account: ${{ secrets.GCP_WORKLOAD_IDENTITY_SA_EMAIL }}
          export_environment_variables: true

      - id: login
        name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: europe-north1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

  build-and-push-to-artifact-registry:
    name: Build and push to Artifact Registry
    runs-on: ubuntu-latest
    needs: authorize

    permissions:
      id-token: write
      contents: read

    env:
      IMAGE_NAME: hello-app
      PROJECT_ID: cloud-core-376009

    steps:
      # - id: checkout
      #   name: Checkout
      #   uses: actions/checkout@v3

      # - id: auth
      #   name: Auth in GCP
      #   uses: google-github-actions/auth@v1
      #   with:
      #     token_format: access_token
      #     workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_NAME }}
      #     service_account: ${{ secrets.GCP_WORKLOAD_IDENTITY_SA_EMAIL }}

      # - id: login
      #   name: Login to Artifact Registry
      #   uses: docker/login-action@v1
      #   with:
      #     registry: europe-north1-docker.pkg.dev
      #     username: oauth2accesstoken
      #     password: ${{ steps.auth.outputs.access_token }}

      - id: build
        name: Build Docker Image
        run: docker build -t $IMAGE_NAME:latest .

      - id: tag
        name: Get tagged
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - id: push
        name: Push to Google Artifact Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            europe-north1-docker.pkg.dev/${{ env.PROJECT_ID }}/docker/hello-app:${{ steps.tag.outputs.short_ref }}
            europe-north1-docker.pkg.dev/${{ env.PROJECT_ID }}/docker/hello-app:latest
