name: Build and push docker image to Artifact Registry

on:
  push:
    branches: [main]

jobs:
  auth:
    name: Authenticate
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - id: checkout
        uses: actions/checkout@v2

      - id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_NAME }}
          service_account: ${{ secrets.GCP_WORKLOAD_IDENTITY_SA_EMAIL }}

      - id: login
        uses: docker/login-action@v1
        with:
          registry: europe-north1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: hello-app
      # PROJECT_ID: cloud-core-376009

      - id: build
        run: docker build -t $IMAGE_NAME:latest .
