name: Build and push docker image to Artifact Registry

on:
  push:
    branches: [main]

jobs:
  build-and-push-to-artifact-registry:
    name: "Build and push to Artifact Registry"
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      IMAGE_NAME: hello-app
      # PROJECT_ID: cloud-core-376009

    steps:
      - id: "checkout"
        name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Auth in GCP"
        id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          token_format: "access_token"
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_NAME }}
          service_account: ${{ secrets.GCP_WORKLOAD_IDENTITY_SA_EMAIL }}

      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: europe-north1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - id: build
        name: Build Docker Image
        run: docker build -t $IMAGE_NAME:latest .
